Update secure_software_development_fundamentals.md
balteravishay/secure-sw-dev-fundamentals pull request #32
Opened 2023-03-06 13:03 UTC by SharonHart

2023-03-12 19:42 UTC, SharonHart commented
@balteravishay @navalev Ready for review

2023-03-14 07:09 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +פרק זה מתאר כיצד לתכנן מערכת תוכנה כך שתהיה מאובטחת, תוך התמקדות בעקרונות אבטחה מרכזיים כגון הרשאות מינימליות, גישור מלא ואימות קלט.
```suggestion
פרק זה מתאר כיצד לתכנן מערכת תוכנה כך שתהיה מאובטחת, תוך התמקדות בעקרונות אבטחה מרכזיים כגון הרשאות מינימליות, גישור (mediation) מלא ואימות קלט.

```

2023-03-14 07:24 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +### מהן עקרונות אבטחתיות בתכנון מערכת תוכנה?
לא בטוח שיש מילה כזו אבטחתיות. מעדיף משהו יותר קרוב לתרגום המקורי:
מהם עקרונות אבטחה בתכנון המערכת

2023-03-14 07:26 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +זכרו שתהליך התכנון, כמו כל תהליך פיתוח תוכנה אחר, לא קורה רק פעם אחת. זהו תרחיש נפוץ לנסות ליישם תוכנה, להבין כי התכנון לא עובד, ולאחר מכן לשנות את התכנון. לעתים קרובות יש לשנות תכנון כאשר אתה משנה א
```suggestion
זכרו שתהליך התכנון, כמו כל תהליך פיתוח תוכנה אחר, אינו חד פעמי. זהו תרחיש נפוץ לנסות ליישם תוכנה, להבין כי התכנון לא עובד, ולאחר מכן לשנות את התכנון. לעתים קרובות יש לשנות תכנון כאשר משנים את מה שהתוכנה עושה. אז תהליך התכנון קורה בכל פעם שאתה חושב על שינוי בפירוק הבעיה שהתוכנה שלך פותרת.

```

2023-03-14 07:29 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +תכנונים מסוימים טובים יותר מאחרים: חלקם קלים יותר לתחזוקה, מהירים יותר וכן הלאה. בפרט, תכנונים מסוימים מאובטחים יותר מאחרים. אין פתרון קסם שמבטיח שהתכנון שלכם מאובטח. אבל אנשים מפתחים תוכנה במשך עשרו
```suggestion
תכנונים מסוימים טובים יותר מאחרים: חלקם קלים יותר לתחזוקה, מהירים יותר וכן הלאה. בפרט, תכנונים מסוימים מאובטחים יותר מאחרים. אין פתרון קסם שמבטיח שהתכנון שלכם מאובטח. אבל מניסיונם של אנשים המפתחים תוכנה במשך עשרות שנים, זוהו סט של *עקרונות תכנון* שיכולים לעזור לך לבחור תכנונים טובים על פני רעים.

```

2023-03-14 07:32 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +עקרונות תכנון המערכת הם מדריכים מדויקים המבוססים על ניסיון ופרקטיקה. במילים אחרות, עקרונות התכנון הם כללי אצבע שיעזרו לכם להימנע מבעוד מועד מתכנון גרוע וינחו אתכם לתכנון טוב במקום זאת. עם זאת, עקרונו
```suggestion
עקרונות תכנון המערכת הם מדריכים מדויקים המבוססים על ניסיון ופרקטיקה. במילים אחרות, עקרונות התכנון הם כללי אצבע שיעזרו לכם להימנע מבעוד מועד מתכנון גרוע וינחו אתכם לתכנון טוב במקום זאת. עם זאת, עקרונות תכנון מאובטח אינם מבטיחים אבטחה; הם כלי עזר לחשיבה, לא תחליף לחשיבה. לדוגמה, לפעמים עיקרון לא יחול בכלל. לפעמים עקרונות מתנגשים; לדוגמה, עיקרון אחד של תכנון מאובטח הוא שמירה על פשטות, אבל לפעמים נדרשת יותר מורכבות כדי לבצע משהו מסויים. במקרים נדירים יותר, יכולות להיות סיבות טובות מבחינה אבטחה שמפרות לחלוטין עיקרון. עם זאת, התוכנה שלך תהיה בדרך כלל מאובטחת יותר על ידי התחשבות בעקרונות תכנון מאובטחים וניסיון ליישם אותם. עקרונות תכנון מאובטחים הם חוכמה מזוקקת, וכדאי לשקול אותם.

```

2023-03-14 07:33 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +כשחושבים על התכנון, צריך לחשוב על אילו רכיבים אתה יכול לסמוך (וכמה), ועל אילו רכיבים אתה לא בהכרח יכול לסמוך. כמה עקרונות תכנון מדברים על *גבול אמון*. גבול האמון הוא פשוט הגבול בין הרכיבים שאתה סומך
```suggestion
כשחושבים על התכנון, צריך לחשוב על אילו רכיבים ניתן לסמוך (וכמה), ועל אילו רכיבים לא בהכרח ניתן לסמוך. כמה עקרונות תכנון מדברים על *גבול אמון*. גבול האמון הוא פשוט הגבול בין הרכיבים שניתן לסמוך עליהם לבין הרכיבים שלא בהכרח ניתן לסמוך עליהם. מיקום גבול האמון תלוי בתוכנה הממפותחת:

```

2023-03-14 07:34 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +* אם אתה כותב יישום בצד השרת, סביר להניח שאתה נותן אמון במה שמריץ את היישום (לדוגמה, המחשב, מערכת ההפעלה וזמן הריצה של הקונטיינר , אם קיים), אך לא במערכות החיצוניות בצד הלקוח (שחלקן עשויות להיות נשלט
```suggestion
* כשכותבים יישום בצד השרת, סביר להניח שנותנים אמון במה שמריץ את היישום (לדוגמה, המחשב, מערכת ההפעלה וזמן הריצה של הקונטיינר , אם קיים), אך לא במערכות החיצוניות בצד הלקוח (שחלקן עשויות להיות נשלטות על-ידי תוקף). גבול האמון הוא בין השרת ללקוחות.

```

2023-03-14 07:38 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +* אם אתה כותב אפליקציה סלולרית (לטלפון חכם) שמדברת עם השרת שבשליטתך, סביר להניח שאתה סומך על השרת המרוחק הזה. אתה לא צריך לסמוך על נתיב התקשורת בין היישום שלך לשרת (אז תרצה להשתמש בTLS כדי להצפין אות
```suggestion
* אם כותבים אפליקציה סלולרית (לטלפון חכם) שמדברת עם השרת שבשליטתנו, סביר להניח שסומכים על השרת המרוחק הזה. לא צריך לסמוך על נתיב התקשורת בין היישום שלנו לשרת (אז נירצה להשתמש בTLS כדי להצפין אותו). בהחלט לא צריך לסמוך על יישומים אחרים בטלפון החכם, אלא אם כן יש סיבה מיוחדת לסמוך עליהם. אז ברור שיש גבול בין היישום שלנו לבין (1) האינטרנט ו-(2) יישומים ניידים אחרים. אמון הוא לעתים קרובות לא מוחלט; אנחנו כנראה סומכים על כך שמערכת ההפעלה של הטלפון החכם תפעל עבור אותו משתמש, אך משתמש זה עשוי להיות תוקף, אז כנראה צריך לוודא שהרשאות גישה (סיקרטס/ secrets) מסוימים לעולם לא יגיעו ליישום הנייד בכלל.

```

2023-03-14 07:38 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +\>\>אם תעקוב אחר עקרונות התכנון של מערכת מאובטחת, תמיד תיצור תוכנה מאובטחת. אמת או שקר?<<
```suggestion
\>\>אם עוקבים אחר עקרונות התכנון של מערכת מאובטחת, תמיד נוצרת תוכנה מאובטחת. אמת או שקר?<<

```

2023-03-14 07:40 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +למרבה הצער, שמירה על עקרונות תכנון של מערכת מאובטחת אינה מבטיחה תוכנה מאובטחת. במקום זאת, הם רק מדריך בעל ערך לדרך זו. אתה עדיין צריך *לחשוב*.
```suggestion
למרבה הצער, שמירה על עקרונות תכנון של מערכת מאובטחת אינה מבטיחה תוכנה מאובטחת. במקום זאת, הם רק מדריך בעל ערך לדרך זו. עדיין צריך *לחשוב*.

```

2023-03-14 07:47 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +1. **הרשאות פחותות**<br> כל משתמש (אנושי) ותוכנה צריכים לפעול תוך שימוש במספר ההרשאות הנמוך ביותר האפשרי. עיקרון זה מגביל את הנזק כתוצאה מטעות או התקפה. היא גם מפחיתה את מספר האינטראקציות הפוטנציאליו
```suggestion
1. **הרשאות פחותות (Least privilege)**<br> כל משתמש (אנושי) ותוכנה צריכים לפעול תוך שימוש במספר ההרשאות הנמוך ביותר האפשרי. עיקרון זה מגביל את הנזק כתוצאה מטעות או התקפה. הוא גם מפחית את מספר האינטראקציות הפוטנציאליות בין תוכניות מורשות, כך שסביר להניח ששימושים לא מכוונים, לא רצויים או לא ראויים בהרשאות יתרחשו פחות.

```

2023-03-14 07:48 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +2. **גישור הרשאות מלא (גם אי-עקיפה)**<br>כל ניסיון גישה חייב להיבדק; מקם את המנגנון כך שלא ניתן יהיה לערער עליו. מילה נרדפת למטרה זו היא אי-עקיפה.
```suggestion
2. **גישור הרשאות מלא (גם אי-עקיפה) (Complete mediation)**<br>כל ניסיון גישה חייב להיבדק; יש למקם את המנגנון כך שלא ניתן יהיה לערער עליו. מילה נרדפת למטרה זו היא אי-עקיפה.

```

2023-03-14 07:57 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +4. **תכנון פתוח**<br>אסור שמנגנון ההגנה יהיה תלוי בידע התוקף. במקום זאת, עליך לפעול כאילו המנגנון ידוע לציבור, ובמקום זאת להסתמך על סודיות של פריטים מעטים יחסית הניתנים לשינוי בקלות כמו סיסמאות או מפ
```suggestion
4. **תכנון פתוח**<br>אסור שמנגנון ההגנה יהיה תלוי בידע התוקף. במקום זאת, עליך לפעול כאילו המנגנון ידוע לציבור, ולהסתמך על סודיות של פריטים מעטים יחסית הניתנים לשינוי בקלות כמו סיסמאות או מפתחות פרטיים. תוקף לא אמור להיות מסוגל לפרוץ למערכת רק בגלל שאינו יודע איך היא עובדת. עקרון "אבטחה באמצעות אלמוניות" בדרך כלל לא עובד.

```

2023-03-14 07:57 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +5. **אל-כשל בברירות מחדל**<br>התקנת ברירת המחדל צריכה להיות ההתקנה המאובטחת. אם לא בטוח שצריך לאפשר משהו, אל תאפשר אותו.
```suggestion
5. **ברירות מחדל מאובטחות**<br>התקנת ברירת המחדל צריכה להיות ההתקנה המאובטחת. אם לא בטוח שצריך לאפשר משהו, אל תאפשרו אותו.

```

2023-03-14 07:59 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +7. **המנגנון הכי פחות נפוץ (גם למזער שיתוף)**<br> יש למזער את הכמות והשימוש במנגנונים משותפים. הימנע משיתוף קבצים, ספריות, שימוש בקרנל של מערכת ההפעלה או מחשבים עם משהו שאינך בוטח בו, מכיוון שהתוקפים
```suggestion
7. **המנגנון הכי פחות נפוץ (גם למזער שיתוף)**<br> יש למזער את הכמות והשימוש במנגנונים משותפים. הימנע משיתוף קבצים, ספריות, שימוש בקרנל (kernel) של מערכת ההפעלה או מחשבים עם משהו שלא ניתן לבטוח בו, מכיוון שהתוקפים עלולים לנצל אותם.

```

2023-03-14 08:01 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +זכרו, עקרונות העיצוב הם פשוט כללי אצבע. כאשר אנו מפרקים את הבעיה כדי לפתור אותה, עלינו לחשוב על עקרונות אלה, מכיוון שהם יעזרו להנחות אותנו ליצירת תוכנה מאובטחת יותר. ישנם מקרים שבהם יהיו לנו סיבות טו
```suggestion
זכרו, עקרונות התכנון הם פשוט כללי אצבע. כאשר אנו מפרקים את הבעיה כדי לפתור אותה, עלינו לחשוב על עקרונות אלה, מכיוון שהם יעזרו להנחות אותנו ליצירת תוכנה מאובטחת יותר. ישנם מקרים שבהם יהיו לנו סיבות טובות *לא* ליישם אותם. עקרונות אלה אינם מחליפים את החשיבה - הם עוזרים *להנחות* אותנו כאשר אנו חושבים.

```

2023-03-14 08:02 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +עקרון "התכנון הפתוח" אומר שאנחנו לא יכולים לסמוך על התוקפים שלא יודעים איך מערכת עובדת. במקום זאת, עלינו לתכנן את המערכות שלנו כך שיישארו מאובטחות גם כאשר התוקף יודע בדיוק איך הן עובדות.
```suggestion
עקרון "התכנון הפתוח" אומר שאנחנו לא יכולים לסמוך על כך שהתוקפים אינם יודעים איך מערכת עובדת. במקום זאת, עלינו לתכנן את המערכות שלנו כך שיישארו מאובטחות גם כאשר התוקף יודע בדיוק איך הן עובדות.

```

2023-03-14 09:36 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +### הרשאות פחותות
```suggestion
### הרשאות פחותות (Least Privilege)

```

2023-03-14 09:37 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +כבר ציינו כי ההרשאות הפחותות הוא עיקרון חשוב של תכנון מאובטח. הרעיון הבסיסי הוא שכל משתמש (אדם או תוכנית) צריך לפעול תוך שימוש בהרשאות המעטות ביותר האפשריות. באופן כללי, לא נאפשר קריאה או כתיבה של מי
```suggestion
כבר ציינו כי עיקרון ההרשאות הפחותות הוא חשוב בתכנון מאובטח. הרעיון הבסיסי הוא שכל משתמש (אדם או תוכנית) צריך לפעול תוך שימוש בהרשאות המעטות ביותר האפשריות. באופן כללי, לא נאפשר קריאה או כתיבה של מידע אלא אם כן עלינו לעשות זאת עבור משתמש זה.

```

2023-03-14 09:39 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +1. **לא ניתן לתוכנית הרשאות מיוחדות (כאשר זה מעשי)**<br>אם ניתן לעשות זאת, נעשה זאת, מכיוון שזה הטוב ביותר מנקודת מבט של אבטחה. לדוגמה, לינוקס תומכת בהפיכת תוכניות **setuid** או **setgid**, כך שפשוט
```suggestion
1. **לא ניתן לתוכנית הרשאות מיוחדות (כאשר זה מעשי)**<br>אם ניתן לעשות זאת, נעשה זאת, מכיוון שזה הטוב ביותר מנקודת מבט של אבטחה. לדוגמה, לינוקס תומכת בהפיכת תוכניות **setuid** או **setgid**, כך שעצם הפעלת התוכנית מעניקה לתוכנית את ההרשאות של בעליה. אם אנו יכולים להימנע לחלוטין משימוש במנגנון זה, נשקול לעשות את זה, מכיוון שזה נותן הרשאות מיוחדות לתוכניות. לעתים קרובות יש חלופות בטוחות יותר; לדוגמה, דרישה מאנשים להתחבר באופן ספציפי עם הרשאות (זוהי המטרה של **SUDO**).

```

2023-03-14 09:41 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +2. **נמזער את ההרשאות המיוחדות שתוכנית מקבלת, כולל מזעור כל הנתונים הנגישים לה**<br>בלינוקס, ייתכן שיש לנו תוכנית עבור (או בשם) קבוצה מיוחדת או משתמש שיש להם רק זכויות ספציפיות, במקום משהו חסוי יותר
```suggestion
2. **נמזער את ההרשאות המיוחדות שתוכנית מקבלת, כולל מזעור כל הנתונים הנגישים לה**<br>בלינוקס, ייתכן שיש לנו תוכנית עבור (או בשם) קבוצה מיוחדת או משתמש שיש להם רק הרשאות ספציפיות, במקום משהו חסוי יותר (כמו root). אם אנו קוראים לממשק שאילתה של מערכת מסד נתונים, נגביל את הההרשאות של משתמש מסד הנתונים שבו משתמש היישום. אם מערכת מסד הנתונים שלנו משתמשת ב- SQL, ייתכן שנוכל להשתמש בפקודה SQL GRANT כדי להגביל את ההרשאות שהתוכנית מקבלת. משתמשי Redis עשויים להשתמש בפקודת ACL של Redis כדי להגביל הרשאות.

```

2023-03-15 06:51 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +3. **נוותר לצמיתות על הרשאות בהקדם האפשרי**<br>  לדוגמה, אם אנו משתמשים במזהי קבוצה שמורים של Linux, מזהי משתמשים או ביכולות שלהם, נשחרר לצמיתות הרשאות נוספות אלה בהקדם האפשרי. בדרך זו, אם ההתקפה מתר
```suggestion
3. **ויתור לצמיתות על הרשאות בהקדם האפשרי**<br>  לדוגמה, אם משתמשים במזהי קבוצה שמורים של Linux (Group IDs), מזהי משתמשים (User IDs) או ביכולות שלהם, נשחרר לצמיתות הרשאות נוספות אלה בהקדם האפשרי. בדרך זו, אם ההתקפה מתרחשת לאחר מכן, התוקפים אינם יכולים לנצל הרשאות אלה.

```

2023-03-15 06:56 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +5. **נחלק את התוכנית למודולים שונים, ונתן הרשאות מיוחדות רק למודול אחד או לכמה מודולים (חלקים מהתוכנית)**  <br>המודול המורשה באופן אידיאלי אפילו לא ייתן אמון מלא בחלקים האחרים של התוכנית שלנו (גם *תכ
```suggestion
5. **נחלק את התוכנית למודולים שונים, וניתן הרשאות מיוחדות רק למודול אחד או לכמה מודולים (חלקים מהתוכנית)**  <br>המודול המורשה באופן אידיאלי אפילו לא ייתן אמון מלא בחלקים האחרים של התוכנית שלנו (גם *תכנון חשוד*). אם נעשה זאת, כאשר חלק כלשהו מהתוכנית שלנו יהיה תחת התקפה, זה יגביל את מה שתוקפים יכולים לעשות באופן מיידי. לדוגמה, ייתכן שנפצל את החלק של תוכנית המיישם ממשק משתמש גרפי מחלק אחר בעל הרשאות. מנגנוני הפרדה כמו קונטיינרים, מכונות וירטואליות, seccomp בלינוקס וסוגים שונים של מעטפות אבטחה יכולים לעזור לנו להפריד חלקים של התוכנית, כך שפגיעה בחלק אחד לא בהכרח תשבור אחר. ***היזהרו:*** *נקפיד להגדיר מנגנונים אלה כדי להפריד באופן מאובטח את המודולים, ולהגביל את ההרשאות בכל חלק.* מנגנוני הפרדה אלה לרוב אינם חסינים בפני תקלות, לכן אל תניחו שהשימוש בהם הופך את התוכנה למאובטחת באופן אוטומטי. עם זאת, הם יכולים להפוך את התוכנה שלנו לקשה יותר לתקיפה ועשויים להפחית את הנזק אם התקפה מצליחה.

```

2023-03-15 06:59 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +6. **נמזער (נגביל) את שטח התקיפה** <br>*שטח התקיפה* הוא מערך הפעולות (לדוגמה, ה- API שלו ויציאות הרשת הפתוחות שלו) שתוקפים פוטנציאלים יכולים לגשת אליהן. לדוגמה, אם אנו מאפשרים גישה ציבורית למתודה כלש
```suggestion
6. **נמזער (נגביל) את שטח התקיפה** <br>*שטח התקיפה* הוא מערך הפעולות (לדוגמה, ה- API שלו ויציאות הרשת הפתוחות שלו) שתוקפים פוטנציאלים יכולים לגשת אליהן. לדוגמה, אם אנו מאפשרים גישה ציבורית למתודה כלשהי, אז אנו נותנים לכל התוקפים גישה למתודה זו - האם אנו בטוחים שאנו צריכים גישה זו? במידת האפשר, נגביל את הפעולות שתוקפים פוטנציאלים יכולים לגשת אליהן. אם לא צריך גישה ציבורית (public), לא נספק גישה ציבורית. בפרט, נמנע מהשארת פעולות דיבאג (debug) במערכות פרודקשן שהתוקפים יכולים לגשת אליהן; פעולות דיבאג הן מקור נפוץ לבעיות.

```

2023-03-15 07:01 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +8. **ארגז חול של התוכנית שלנו**<br>נפעיל בכוונה את התוכנית (או חלק ממנה) בסביבה עם יכולות מוגבלות במכוון.
```suggestion
8. **סאנדבוקס (Sandbox) של התוכנית שלנו**<br>נפעיל בכוונה את התוכנית (או חלק ממנה) בסביבה עם יכולות מוגבלות במכוון.

```

2023-03-15 07:03 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> + הרשאות שגויות הן סיבה נפוצה כל כך לפגיעויות אבטחה שהן מדרגות במקום ה 22 ב- 25 הגדולות ב 2022 CWE  ובמקום ה 15 ב- 25 הגדולות ב CWE 2019. זהו         [CWE-732](https://cwe.mitre.org/data/definitions/7
```suggestion
 הרשאות שגויות הן סיבה נפוצה כל כך לפגיעויות אבטחה שהן מדרגות במקום ה 22 ב- 25 הגדולות ב 2022 CWE  ובמקום ה 15 ב- 25 הגדולות ב CWE 2019. זהו         [CWE-732](https://cwe.mitre.org/data/definitions/732.html) (*הקצאת הרשאה שגויה עבור משאב קריטי*). הרשאות שגויות גרועות במיוחד אם  הרשאות *ברירת המחדל* אינן מאובטחות; המקרה המיוחד הוא [CWE-276](https://cwe.mitre.org/data/definitions/276.html) (*הרשאות ברירת מחדל שגויות*).

```

2023-03-15 07:06 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +בעת פיתוח יישומים מבוססי אינטרנט, לא נאפשר למשתמשים לגשת (לקרוא) לקבצים כגון  קבצי **ה include והקונפיגורציה** של השרת. נתונים אלה עשויים לספק בטעות מספיק מידע (למשל, סיסמאות) כדי לפרוץ למערכת. אם אנ
```suggestion
בעת פיתוח יישומים מבוססי אינטרנט, לא נאפשר למשתמשים לגשת (לקרוא) לקבצים כגון  קבצי **ה include והקונפיגורציה** של השרת. נתונים אלה עשויים לספק בטעות מספיק מידע (למשל, סיסמאות) כדי לפרוץ למערכת. אם משתמשים בשרת אינטרנט מסורתי, נשמור את כל מה שאיננו צריכים כדי לשרת ישירות משתמשים מחוץ ל"שורש התיעוד" (**DOCROOT);** בדרך זו, התוקפים אינם יכולים אפילו לבקש את המידע בקלות. נמנע הנגשה של קבצים שידוע לנו שאין להנגיש ישירות (כגון קבצי **include**).

```

2023-03-15 07:08 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +לא נאפשר למשתמשים לכתוב קבצי תצורת מערכת (קונפיגורציה) כברירת מחדל (לדוגמה, קבצי מערכת ב- **etc/** בלינוקס וביוניקס), ובמידת האפשר, נשקול למנוע קריאות גם על ידי משתמשים רגילים. הבעיה היא שמנהלי מערכת
```suggestion
לא נאפשר למשתמשים לכתוב קבצי תצורת מערכת (קונפיגורציה) כברירת מחדל (לדוגמה, קבצי מערכת ב- **etc/** בלינוקס וביוניקס), ובמידת האפשר, נשקול למנוע קריאות גם על ידי משתמשים רגילים. הבעיה היא שמנהלי מערכת מכניסים לעתים קרובות סיסמאות ומפתחות לקבצי תצורה. אם יש סיבות להעניק הרשאות קריאה רחבות יותר לחלק מהמידע על תצורת המערכת (לדוגמה,  ב- **etc/**), נשקול ליצור ספריית תצורת מערכת במקום קובץ תצורת מערכת שבו שם הספריה מסתיים באופן קונבנציונלי ב- **.d**. ספריות תצורת מערכת הן לעתים קרובות טובות יותר בכל מקרה, מכיוון שהן הופכות את השימוש לטריוויאלי עבור מנהלי חבילות להוסיף ולהסיר קבצי תצורה ספציפיים. מבחינת אבטחה, ספריות תצורת מערכת לא רק מפחיתות את הסיכון לשגיאות, אלא שלקבצים ספציפיים (כגון קבצים עם מפתחות סודיים וסיסמאות) יכולות להיות הרשאות מוגבלות יותר. אם אנו משתמשים בספריית תצורת מערכת, זה פחות בעייתי לאפשר למשתמש לקרוא, כי זה הרבה יותר קל להגן על המפתחות הסודיים וסיסמאות.

```

2023-03-15 07:11 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +אם אנו מיישמים API חיצוני (לדוגמה, עם REST או GraphQL), לא נספק פעולת "כתיבה" אלא אם כן אנו מצפים שייעשה בה שימוש. אם אנו מאפשרים כתיבה, ננסה להגביל באופן מקסימלי *את מי* שכותב. לדוגמה, יש בעלים של נ
```suggestion
אם אנו מיישמים API חיצוני (לדוגמה, עם REST או GraphQL), לא נספק פעולת "כתיבה" אלא אם כן אנו מצפים שייעשה בה שימוש. אם אנו מאפשרים כתיבה, ננסה להגביל באופן מקסימלי *את מי* שכותב. לדוגמה, אפשרו רק לבעלים של נתונים ספציפיים לשנות נתונים אלה, במקום לאפשר לכל אחד לשנות דבר מה. אם זה מעשי, נתכנן את התוכנה כך שהיא לא תוכל לכתוב נתונים *גם* אם הם עורערו על ידי תוקף (אם כי לעתים קרובות זה לא מעשי).

```

2023-03-15 07:52 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +למרבה הצער, מקובל לנהל הרשאות בצורה לא נכונה. לדוגמה, ישנם מקרים רבים שבהם תוכניות לא הצליחו לשחרר הרשאות בכל המקרים (למשל, משום שהעלאת חריגה דילגה על הקוד שהשמיט הרשאות, או משום שהקוד שהיה אמור לשחר
```suggestion
למרבה הצער, מקובל לנהל הרשאות בצורה לא נכונה. לדוגמה, ישנם מקרים רבים שבהם תוכניות לא הצליחו לשחרר הרשאות בכל המקרים (למשל, משום שהעלאת או זריקת אקספשן (Exception) דילגה על הקוד שהשמיט הרשאות, או משום שהקוד שהיה אמור לשחרר הרשאות אינו פועל בכל המקרים).

```

2023-03-15 08:08 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +בכל פעם שתוכנית מקבלת בקשה, לפחות ממקור שהתוכנית אינה יכולה לתת בו אמון מלא (הוא נמצא מחוץ לגבולות האמון), התוכנית חייבת לבדוק את הבקשה. דוגמאות לבדיקות אבטחה הן בדיקה שהבקשה מאושרת ושהקלט תקף לפני ש
```suggestion
בכל פעם שתוכנית מקבלת בקשה, לפחות ממקור שהתוכנית אינה יכולה לתת בו אמון מלא (הוא נמצא מחוץ לגבולות האמון), התוכנית חייבת לבדוק את הבקשה. דוגמאות לבדיקות אבטחה הן בדיקה שהבקשה מאושרת ושהקלט תקף לפני שאנו פועלים על סמך נתונים אלה. עיקרון זה נקרא גם *אי-עקיפה*, משום שהנקודה היא שאסור לתוקפים לעקוף בדיקות אבטחה.

```

2023-03-15 08:10 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +  זה בסדר אם מטרתו היא להיות בדיקה מהירה כדי להתמודד עם טעויות מקריות. אבל מכיוון שהתוקפים יכולים לשלוט בדפדפן האינטרנט שלהם, בדיקת אורך מקסימלית זו היא טריוויאלית לעקוף. תוקפים יכולים לשלוח בקלות קל
```suggestion
  זה בסדר אם מטרתו היא להיות בדיקה מהירה כדי להתמודד עם טעויות מקריות. אבל מכיוון שהתוקפים יכולים לשלוט בדפדפן האינטרנט שלהם, בדיקת אורך מקסימלית זו היא טריוויאלית לעקיפה. תוקפים יכולים לשלוח בקלות קלט ארוך בהרבה. לא ניתן *לסמוך* על דפדפן האינטרנט שיבצע עבורך בדיקה רלוונטית לאבטחה אם התוקפים יכולים לשלוט בדפדפן האינטרנט או להחליף אותו.

```

2023-03-15 08:12 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +תכנון לא מאובטח קשור ונפוץ הוא המקום שבו קוד נשלח לדפדפני אינטרנט, לדוגמה, כ- JavaScript או WebAssembly (WASM), וקוד זה מבצע בדיקות אבטחה לפני שליחת הנתונים שלו לשרת. ברוב המצבים, תוקפים יכולים לשלוט
```suggestion
תכנון לא מאובטח קשור ונפוץ הוא המקום שבו קוד נשלח לדפדפני אינטרנט, לדוגמה, כ- JavaScript או WebAssembly (WASM), וקוד זה מבצע בדיקות אבטחה לפני שליחת הנתונים שלו לשרת. ברוב המצבים, תוקפים יכולים לשלוט בדפדפן האינטרנט, בזמן שהשרת נמצא בשליטתך, כך ששוב, לא ניתן לסמוך על שום דבר שדפדפן האינטרנט עושה. במילים אחרות, כל בדיקות אבטחה בקוד שנשלח לדפדפן יכולות להיעקף באופן טריוויאלי על ידי תוקפים, שכן התוקפים שולטים בדפדפני האינטרנט שלהם. בעיה קשורה היא מתן גישה ישירה למסד נתונים למשתמשים לא מהימנים. לעתים קרובות משתמשים אינם זקוקים לגישה מלאה, ולכן זה נותן למשתמשים הרבה יותר הרשאות ממה שהם צריכים (תוך הפרת ההרשאה הפחותה), וגישה כזו יכולה להקשות על מניעת עקיפת בדיקות אבטחה. האיור הבא מציג טעות זו:

```

2023-03-15 08:14 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +האיור הבא מציג עיצוב דומה אך מאובטח; שים לב שכל הבדיקות הקשורות לאבטחה נעשות בשרת, שכן במקרה זה, זו המערכת שאנו יכולים לסמוך עליה. היא גם מונעת גישה ישירה למסד נתונים, וזה לעתים קרובות רעיון טוב אם מ
```suggestion
האיור הבא מציג עיצוב דומה אך מאובטח; שימו לב שכל הבדיקות הקשורות לאבטחה נעשות בשרת, שכן במקרה זה, זו המערכת שאנו יכולים לסמוך עליה. היא גם מונעת גישה ישירה למסד נתונים, וזה לעתים קרובות רעיון טוב אם משתמשים אינם זקוקים לגישה ישירה:

```

2023-03-15 08:16 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +תכנון מערכת לא מאובטח נפוץ דומה הוא קוד באפליקציות סלולריות לסמארטפון שעושה את כל בדיקות האבטחה לפני שליחת הנתונים שלו לשרת. שוב, איננו יכולים להניח כי בדיקות אבטחה כלשהן ביישום הנייד אכן יבוצעו. תוק
```suggestion
תכנון מערכת לא מאובטח נפוץ דומה הוא קוד באפליקציות סלולריות לסמארטפון שעושה את כל בדיקות האבטחה לפני שליחת הנתונים שלו לשרת. שוב, איננו יכולים להניח כי בדיקות אבטחה כלשהן ביישום הנייד אכן יבוצעו. תוקפים יכולים לשנות את היישום הנייד, או לכתוב יישום אחר, כדי לעקוף את כל הבדיקות שבוצעו ביישום הנייד. אם אנו כותבים יישום נייד לסמארטפון, אנו גם בדרך כלל לא יכולים לסמוך על היישומים האחרים - היישומים האחרים עשויים בעצמם להיות זדוניים!

```

2023-03-15 08:17 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +אם אנו כותב דפדפן אינטרנט, לדוגמה, נצטרך לסמוך על שירותי מערכת ההפעלה המקומיים, אך אנו בהחלט לא יכול לסמוך על שרתי אינטרנט מרוחקים ושרירותיים - חלק מאותם שרתי אינטרנט מרוחקים עלולים לשלוח לנו נתונים
```suggestion
אם אנו כותבים דפדפן אינטרנט, לדוגמה, נצטרך לסמוך על שירותי מערכת ההפעלה המקומיים, אך אנו בהחלט לא יכול לסמוך על שרתי אינטרנט מרוחקים ושרירותיים - חלק מאותם שרתי אינטרנט מרוחקים עלולים לשלוח לנו נתונים זדוניים!

```

2023-03-15 08:20 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +באפשרותנו להשתמש ב- JavaScript בצד הלקוח, ב- WebAssembly בצד הלקוח וביישומים ניידים - זו לא הבעיה. אנו יכולים לכתוב גם דפדפני אינטרנט! הבעיה היא מתן אמון במערכת שעשויה להיות תחת שליטתו של תוקף. אם יש
```suggestion
באפשרותנו להשתמש ב- JavaScript בצד הלקוח, ב- WebAssembly בצד הלקוח וביישומים ניידים - זו לא הבעיה. אנו יכולים לכתוב גם דפדפני אינטרנט! הבעיה היא מתן אמון במערכת שעשויה להיות תחת שליטתו של תוקף. אם יש לנו מערכת שרת-לקוח מבוססת אינטרנט, לדוגמה, בדרך כלל הקוד הפועל בשרת (שאנו שולטים בו) חייב לבצע את כל בדיקות האבטחה. אחרי הכל, תוקפים יכולים לבנות או לשנות אפליקציות לקוח משלהם, כולל JavaScript שנשלח ללקוח שלהם על ידי שרת. זה בסדר להריץ בדיקות על מערכת שאנו לא סומכים עליה באופן מלא אם אנו רוצה לספק תגובה מהירה לטעויות לא מכוונות. אבל זה לא מספיק - עבור אבטחה, כל בדיקות האבטחה צריך להיעשות (או  להיעשות מחדש) על מערכת שאנו יכולים לסמוך עליה באופן מלא. באפשרותנו להפעיל בדיקות אלה בצד השרת באמצעות JavaScript, WebAssembly או כל דבר אחר שבוטחים בו - אך עלינו להפעיל את הבדיקות במערכת שניתן לסמוך עליה.

```

2023-03-15 08:26 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +* אם אנו מנסים לאבטח משחקים במחשב נייד / שולחני, ואנו לא סומכים על המחשב הנייד / השולחני, יש מערכות נגד רמאויות. אבל מערכות נגד רמאויות נשברות באופן שגרתי. עדיף לנו לקיים אירועים פיזיים שבהם כל המחשב
```suggestion
* אם אנו מנסים לאבטח משחקים במחשב נייד / שולחני, ואנו לא סומכים על המחשב הנייד / השולחני, יש מערכות נגד רמאויות. אבל מערכות נגד רמאויות נשברות באופן שגרתי. עדיף לנו לקיים אירועים פיזיים שבהם כל המחשבים הניידים / המחשבים השולחניים נמצאים בבעלותנו.

```

2023-03-15 08:28 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +1. **מנגנון חסכוני (גם פשטות)**. המערכת, בפרט החלק שהאבטחה תלויה בו, צריכה להיות פשוטה וקטנה ככל האפשר. זה הופך את החלק הזה של המערכת לקל יותר לבדיקה וקשה יותר לטעות בו. כמובן, תוכנה מודרנית מתבקשת ל
```suggestion
1. **מנגנון חסכוני (גם פשטות)**. המערכת, בפרט החלק שהאבטחה תלויה בו, צריכה להיות פשוטה וקטנה ככל האפשר. זה הופך את החלק הזה של המערכת לקל יותר לבדיקה וקשה יותר לטעות בו. כמובן, תוכנה מודרנית מתבקשת לעתים קרובות לספק הרבה פונקציונליות, אז אנו בדרך כלל לא יכולים לעשות הכל פשוט מאוד, אבל אנו יכולים לפחות לעבוד כדי להפוך את החלק שהאבטחה תלויה בו לפשוט ככל האפשר.

```

2023-03-15 08:33 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +5. **המנגנון הכי פחות נפוץ (גם למזער שיתוף).** נצמצם את הכמות והשימוש במנגנונים משותפים אם למשתפים יש הרשאות שונות. נמנע משיתוף קבצים, ספריות, ביצוע בקרנל של מערכת הפעלה או מחשבים עם משהו שאנינו בוטח
```suggestion
5. **המנגנון הכי פחות נפוץ (גם למזער שיתוף).** נצמצם את הכמות והשימוש במנגנונים משותפים אם למשתפים יש הרשאות שונות. נמנע משיתוף קבצים, ספריות, ביצוע בקרנל של מערכת הפעלה או מחשבים עם משהו שאנחנו בוטחים בו, מכיוון שהתוקפים עלולים לנצל אותם. כמובן, במקרים רבים זה בא על חשבון גורמים אחרים. דוגמה ברורה היא שירותי ענן: במקרים מסוימים, שימוש בשירות ענן עלול לגרום לתוכנית שלך לפעול בסביבה משותפת עם יריב. במקרה של שירותי ענן, לעתים קרובות ישנם גורמים מקלים שהופכים אותם למקובלים (לדוגמה, ספק שירותי הענן עשוי לספק שורה של אמצעים כדי לספק בידוד טוב יותר, ו/או עשוי להיות צוות מנוסה יותר שמגן ומנטר את המערכות טוב יותר מאשר שאנו יכולים). עם זאת, זה עדיין נכון שכל דבר שאנו משתפים עם תוקפים עלול להוסיף דרך נוספת שבה הוא יותקף. אם שיתוף כזה מסוכן מדי עבור היישום שלך, ניתן לבחור חלופות עם פחות שיתוף (כגון ענן של לקוח יחיד או ענן פרטי). במקרים מסוימים שיתוף יכול להפחית עלויות אך להגביר את סיכוני האבטחה. ההחלטה הטובה ביותר תלויה בנסיבות, וכל מה שעקרונות העיצוב יכולים לעשות הוא לעזור לנו לזהות את הפשרה.

```

2023-03-15 08:36 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +[!] הפיכת קוד המקור לקשה להבנה (למשל, שימוש מעורפלים) כך שיהיה קשה יותר לזהות פגיעויות. {{ נבחר: לא, אם קוד המקור קשה יותר להבנה, אז יהיה קשה יותר למפתחים להפוך אותו למאובטח מלכתחילה. אתה צריך לשאוף
```suggestion
[!] הפיכת קוד המקור לקשה להבנה (למשל, שימוש בשמות מעורפלים) כך שיהיה קשה יותר לזהות פגיעויות. {{ נבחר: לא, אם קוד המקור קשה יותר להבנה, אז יהיה קשה יותר למפתחות להפוך אותו למאובטח מלכתחילה. צריך לשאוף לשמור על המערכת פשוטה ככל האפשר. }}

```

2023-03-15 08:39 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +עקרונות תכנון רבים אחרים הוצעו, בהתבסס על בעיות שקרו למערכות קודמות. כעת, נסתכל על כמה עקרונות עיצוב אחרים שאנו צריכים לשקול.
```suggestion
עקרונות תכנון רבים אחרים הוצעו, בהתבסס על בעיות שקרו למערכות קודמות. כעת, נסתכל על כמה עקרונות תכנון אחרים שאנו צריכים לשקול.

```

2023-03-15 08:39 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> + *מרוץ תהליכים* מתרחש כאשר ההתנהגות הנכונה של מערכת תלויה ברצף האירועים, אך אין שליטה על רצף זה. מרוצי תהליכים כוללים בדרך כלל תהליך אחד או יותר או ת'רדים שניגשים למשאב משותף, אך גישה מרובה זו לא נשל
```suggestion
 *מרוץ תהליכים* מתרחש כאשר ההתנהגות הנכונה של מערכת תלויה ברצף האירועים, אך אין שליטה על רצף זה. מרוצי תהליכים כוללים בדרך כלל תהליך אחד או יותר או ת'רדים (Threads) שניגשים למשאב משותף, אך גישה מרובה זו לא נשלטה כראוי.

```

2023-03-15 08:45 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +לרוב השפות יש שגרה או פקודה ליצור קבצים זמניים באופן מאובטח; השתמשו בהם היכן שהם זמינים. ב- Python מודול tempfile יכול ליצור קבצים זמניים באופן מאובטח. סקריפטים של Shell יכולים להשתמש בפקודה mktemp כ
```suggestion
לרוב השפות יש פונקציה או פקודה ליצור קבצים זמניים באופן מאובטח; השתמשו בהם היכן שהם זמינים. ב- Python מודול tempfile יכול ליצור קבצים זמניים באופן מאובטח. סקריפטים של Shell יכולים להשתמש בפקודה mktemp כדי ליצור קבצים זמניים באופן מאובטח.

```

2023-03-15 08:47 UTC, balteravishay commented on translations/he/secure_software_development_fundamentals.md
> +פגמים קורים! אבל הם לא צריכים להפוך לפגיעויות. במקום זאת, ננסה לתכנן את המערכת שלנו כך שפגם בודד יהיה הרבה פחות סביר שיגרום לסכנה מוחלטת. זהו בעצם יישום ספציפי של עקרון ההרשאות הפחותות, אך אם אנו חוש
```suggestion
פגמים קורים! אבל הם לא צריכים להפוך לפגיעויות. במקום זאת, ננסה לתכנן את המערכת שלנו כך שיהיה הרבה פחות סביר שפגם בודד יגרום לסכנה מוחלטת. זהו בעצם יישום ספציפי של עקרון ההרשאות הפחותות, אך אם אנו חושבים באופן ספציפי על הפיכת המערכת לקשה לערעור *גם* כאשר יש בה פגם, אנו עשויים לזהות צעדים אחרים שניתן לנקוט.

```

2023-03-15 08:51 UTC, balteravishay requested changes
thanks for your time and contribution! this is amazing work. left some comments and suggestions.

2023-03-15 09:48 UTC, SharonHart commented
@balteravishay Awesome review and great catches. Pushed all the fixes, thanks.

2023-03-16 08:05 UTC, merged